language: ruby
bundler_args: --binstubs
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
before_install:
  - sudo apt-get install -qq jpegoptim libjpeg-progs
after_success:
  - script/quality
matrix:
  include:
    - rvm: 2.0.0
      env: COVERAGE=true
